---
- name: Create directories
  file: path={{item}} state=directory
  with_items:
    - "{{pl_elastichq_directory}}"
    - "{{pl_elastichq_directory}}/logs"

- name: Install python3
  apt: name={{item}} state=present
  with_items:
  - python3
  - python3-pip

- name: Check out repo
  git: repo='{{pl_elastichq_repo}}' dest='{{pl_elastichq_directory}}'

- name: Install pip packages
  pip: requirements='{{pl_elastichq_directory}}/requirements.txt' executable=pip3 #virtualenv='{{pl_elastichq_virtualenv}}'

- name: Copy elastichq init scripts
  template: src=elastichq.j2 dest=/etc/init.d/elastichq mode=0755
